name: Build on macOS

on:
  push:
    branches:
      - master

jobs:
  build-osx-arm64:
    runs-on: macos-14
    defaults:
      run:
        shell: sh -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mokit-env
          environment-file: recipe/env.yaml
          python-version: 3.11
          architecture: arm64
      - name: Build the package
        run: |
          conda info
          conda activate mokit-env
          wget "https://gitlab.com/jxzou/mokit/-/raw/master/pyproject.toml"
          rattler-build build --recipe recipe --output-dir output -c conda-forge --experimental
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mokit-osx-arm64
          path: output/*/*.conda
      - name: Upload to Anaconda.org
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA }}
        run: |
          rattler-build upload anaconda -o mokit -c cf ./output/*/*.conda
