name: Build on Windows

on:
  push:
    branches:
      - master
      - windows
    paths:
      - "recipe/*"
      - ".github/workflows/windows.yml"

jobs:
  build-win-64:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v2
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mokit-env
          environment-file: recipe/env.yaml
          python-version: 3.11
      - name: Build the package
        run: |
          conda info
          conda activate mokit-env
          Write-Host "FC=$env:FC"
          Write-Host "F77=$env:F77"
          Write-Host "F90=$env:F90"
          Write-Host "CC=$env:CC"
          Write-Host "CXX=$env:CXX"
          Write-Host "MAKE=$env:MAKE"
          Write-Host "BUILD_PREFIX=$env:BUILD_PREFIX"
          Write-Host "PREFIX=$env:PREFIX"
          Invoke-WebRequest -Uri "https://gitlab.com/jxzou/mokit/-/raw/master/pyproject.toml" -OutFile pyproject.toml
          rattler-build build --recipe recipe --output-dir output -c conda-forge --experimental
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mokit-win-64
          path: output/*/*.conda
      - name: Upload to Anaconda.org
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA }}
        run: |
          rattler-build upload anaconda -o mokit ./output/*/*.conda
